//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBTallerEntities : DbContext
    {
        public DBTallerEntities()
            : base("name=DBTallerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<det_producto> det_producto { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<reservacion> reservacion { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
